### PR TITLE
add shim

### PR DESCRIPTION
**Pull request by calvinmetcalf**
broken out from #4

### CODE REVIEW

**Comment by dcousens** [comment]
This PR blocks `2.0.2`, as currently the repo is not semver compatible with `2.x.y`.

**Comment by calvinmetcalf** [comment]
i figure this could be 3.1.0 as it adds a feature in a backwards compatible way

**Comment by dcousens** [comment]
@calvinmetcalf the original repository was being used as a browserify shim and compatibility layer for node 11 style pbkdf2 in node 10.
Publishing this as `3.0.0` means it has thrown away its the compatibility layer, and now we're re-introducing it in `3.1.0`?    How confusing...

I was hoping to review this first and just publish this as `3.0.0`, representing a changed API but none the less no change in overall functionality.

**Comment by dcousens** [comment]
Gah, it was published already.  I suggest we unpublish it and re-publish as `3.0.1` later; as is, this repository is broken for non-browserify usage.

**Comment by calvinmetcalf** [comment]
ok looks like you unpublished it, I get what your talking about  it would break using non sha1 hashes in 0.10 because it defaults to native, sorry about that

**Comment by calvinmetcalf** [comment]
ok so this would be 3.0.1 right ?

**Comment by dcousens** [comment]
Published as `3.0.1`.

**Pull request merged**
