### PR TITLE
fix bug in encoding

### PR DESCRIPTION
**Pull request by calvinmetcalf**
basically you can't send a buffer to a different process so I had to stringify it, but I was just doing toString and that was aparently not round tripping back to a buffer correctly, there would have also likely been an issue with passwords that included weird non printable charicters

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
I also (as a separate commit) added 0.12 and iojs to the test suite

**Comment by dcousens** [comment]
I'm not sure how we didn't catch this with tests though?

**Comment by dcousens** [comment]
[published as 3.0.2](https://github.com/crypto-browserify/pbkdf2-compat/commit/c315c35d28accb2e8c7d3a65ca4111527c4a9c1e)

**Comment by calvinmetcalf** [comment]
All the tests had string based salts I'm pretty sure

**Pull request merged**
